### ISSUE TITLE
Breaking change

### ISSUE THREAD

**Issue by mo8it** [ctron/colored_json#7]
The commit https://github.com/ctron/colored_json/commit/df5c79b33e199a8bca7c02a1e5f29867604fe1bd is not only a feature as listed in the release notes, but it can be a breaking change as shown in the issue https://github.com/01mf02/jaq/issues/120 which is fixed by https://github.com/01mf02/jaq/pull/122

You could either just add this possible issue as a note somewhere or yank `v3.3.0` and publish `v4.0.0`.

**Comment by ctron** [comment]
Ok, released 4.0.0 and yanked 3.3.0. I should have been a seamless upgrade, and looked good with other cases. Sorry for the troubles.
